### ISSUE TITLE
Maintainer access

### ISSUE THREAD

**Issue by paulbovbel** [clearpath-gbp/zbar_ros-release#1]
Hi @mikepurvis, I've added @ijnek as a maintainer to zbar_ros for ROS2 - would you mind granting him access to this repository as well please? I don't have permissions.

**Comment by ijnek** [comment]
@paulbovbel It seems like @mikepurvis has been away from Github for a while, is there anyone else you could allocate this task?

**Comment by paulbovbel** [comment]
Thanks Mike!

**Comment by ijnek** [comment]
@paulbovbel Is there a review process for zbar_ros? If I've got enhancements (such as passing through the corner points of the QR code detected by zbar through to the ROS message), should I request a review or not?

**Comment by paulbovbel** [comment]
I'd be happy to review @ijnek, feel free to tag me anytime. And feel free to cut a release of zbar_ros for ROS2 when you're ready, let me know if you need any help with that.

**Comment by ijnek** [comment]
Great, thanks @paulbovbel.

**Comment by ijnek** [comment]
@paulbovbel or @mikepurvis, I can't release the package as the [zbar maintainers team only has Read access](https://github.com/orgs/ros-drivers-gbp/teams/zbar-maintainers/repositories) to this repo. Would you be able to change this to Write or Admin? Thanks.

Edit: Comment has been moved to another issue #2 .
