### ISSUE TITLE
Can't release pakage because zbar maintainers team only has read access

### ISSUE THREAD

**Issue by ijnek** [clearpath-gbp/zbar_ros-release#2]
@paulbovbel or @mikepurvis, I can't release the package as the [zbar maintainers team only has Read access](https://github.com/orgs/ros-drivers-gbp/teams/zbar-maintainers/repositories) to this repo. Would you be able to change this to Write or Admin? Thanks.

**Comment by mikepurvis** [comment]
Sorry about that; please try now.

**Comment by ijnek** [comment]
I've put a release up at https://github.com/ros/rosdistro/pull/32228, but recently, all release repos seems to have been moved to [ros2-gbp](https://github.com/ros2-gbp), so I'm checking up to see if we have to move zbar_ros-release to ros2-gbp too.
